### ISSUE TITLE
Failing to load LSP

### ISSUE THREAD

**Issue by aaronjanse** [nix-community/vscode-nix-ide#152]
I love this extension, and I use it for developing [rnix-lsp](https://github.com/nix-community/rnix-lsp).

I noticed that on v0.1.12, the extension works as expected. However, after updating to v0.1.15, the LSP fails to load. I see the following error message in `Log (Extension Host)`, which is resolved by rolling back to v0.1.12:

```
[2021-08-19 10:38:55.611] [exthost] [error] Error: Cannot find module 'vscode-languageclient/node'
Require stack:
- /home/ajanse/.vscode/extensions/jnoortheen.nix-ide-0.1.15/dist/client.js
- /home/ajanse/.vscode/extensions/jnoortheen.nix-ide-0.1.15/dist/extension.js
- /nix/store/gdzyg1lc5rxvm3rghnc3anjip5h5bn2q-vscode-1.57.1/lib/vscode/resources/app/out/vs/loader.js
- /nix/store/gdzyg1lc5rxvm3rghnc3anjip5h5bn2q-vscode-1.57.1/lib/vscode/resources/app/out/bootstrap-amd.js
- /nix/store/gdzyg1lc5rxvm3rghnc3anjip5h5bn2q-vscode-1.57.1/lib/vscode/resources/app/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
	at Module._load (internal/modules/cjs/loader.js:779:27)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
	at Function.n._load (/nix/store/gdzyg1lc5rxvm3rghnc3anjip5h5bn2q-vscode-1.57.1/lib/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:27815)
	at Function.E._load (/nix/store/gdzyg1lc5rxvm3rghnc3anjip5h5bn2q-vscode-1.57.1/lib/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:24567)
	at Function.c._load (/nix/store/gdzyg1lc5rxvm3rghnc3anjip5h5bn2q-vscode-1.57.1/lib/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:59196)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at v (/nix/store/gdzyg1lc5rxvm3rghnc3anjip5h5bn2q-vscode-1.57.1/lib/vscode/resources/app/out/vs/loader.js:4:698)
	at Object.<anonymous> (/home/ajanse/.vscode/extensions/jnoortheen.nix-ide-0.1.15/dist/client.js:15:16)
	at Module.u._compile (/nix/store/gdzyg1lc5rxvm3rghnc3anjip5h5bn2q-vscode-1.57.1/lib/vscode/resources/app/out/vs/loader.js:4:1315)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
	at Function.n._load (/nix/store/gdzyg1lc5rxvm3rghnc3anjip5h5bn2q-vscode-1.57.1/lib/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:27815)
	at Function.E._load (/nix/store/gdzyg1lc5rxvm3rghnc3anjip5h5bn2q-vscode-1.57.1/lib/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:24567)
	at Function.c._load (/nix/store/gdzyg1lc5rxvm3rghnc3anjip5h5bn2q-vscode-1.57.1/lib/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:59196)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at v (/nix/store/gdzyg1lc5rxvm3rghnc3anjip5h5bn2q-vscode-1.57.1/lib/vscode/resources/app/out/vs/loader.js:4:698)
	at Object.<anonymous> (/home/ajanse/.vscode/extensions/jnoortheen.nix-ide-0.1.15/dist/extension.js:17:16)
	at Module.u._compile (/nix/store/gdzyg1lc5rxvm3rghnc3anjip5h5bn2q-vscode-1.57.1/lib/vscode/resources/app/out/vs/loader.js:4:1315)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
	at Function.n._load (/nix/store/gdzyg1lc5rxvm3rghnc3anjip5h5bn2q-vscode-1.57.1/lib/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:27815)
	at Function.E._load (/nix/store/gdzyg1lc5rxvm3rghnc3anjip5h5bn2q-vscode-1.57.1/lib/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:24567)
	at Function.c._load (/nix/store/gdzyg1lc5rxvm3rghnc3anjip5h5bn2q-vscode-1.57.1/lib/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:59196)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at require (internal/modules/cjs/helpers.js:88:18)
	at Function.t [as __$__nodeRequire] (/nix/store/gdzyg1lc5rxvm3rghnc3anjip5h5bn2q-vscode-1.57.1/lib/vscode/resources/app/out/vs/loader.js:5:101)
	at m._loadCommonJSModule (/nix/store/gdzyg1lc5rxvm3rghnc3anjip5h5bn2q-vscode-1.57.1/lib/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:25973)
	at m._doActivateExtension (/nix/store/gdzyg1lc5rxvm3rghnc3anjip5h5bn2q-vscode-1.57.1/lib/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:12617)
	at m._activateExtension (/nix/store/gdzyg1lc5rxvm3rghnc3anjip5h5bn2q-vscode-1.57.1/lib/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:11676)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 0)
```

**Comment by jnoortheen** [comment]
Thanks for reporting. I released a new version with the fix. Can you test it?

**Comment by jnoortheen** [comment]
@aaronjanse any updates?
